// src/components/ui/button.tsx
import * as React from "react"

import { cva, type VariantProps } from "class-variance-authority"

import { focusRing } from "~/utils/styles"
import { cn } from "~/utils/utils"

import { BaseButton, BaseButtonProps } from "../base/BaseButton"

const buttonVariants = cva(
  [
    "inline-flex items-center justify-center gap-2 truncate rounded-md text-sm font-medium disabled:pointer-events-none disabled:opacity-50",
    focusRing,
  ],
  {
    variants: {
      variant: {
        key: "bg-zinc-700/50 text-accent-foreground hover:bg-zinc-700/75",
        destructive:
          "border border-red-400 bg-red-400/5 text-red-400 hover:bg-red-400/15",
        ghost:
          "border border-input bg-background hover:bg-accent hover:text-accent-foreground",
        flat: "hover:bg-accent hover:text-accent-foreground",
        link: "text-primary underline-offset-4 hover:underline",
      },
      size: {
        md: "h-10 shrink-0 px-4",
        sm: "h-8 px-3",
      },
    },
    defaultVariants: {
      variant: "key",
      size: "md",
    },
  }
)

export type ButtonProps = BaseButtonProps & VariantProps<typeof buttonVariants>

const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
  ({ className, variant, size, ...props }, ref) => {
    return (
      <BaseButton
        className={cn(buttonVariants({ variant, size, className }))}
        ref={ref}
        {...props}
      />
    )
  }
)
Button.displayName = "Button"

export { Button, buttonVariants }

// src/lib/Button.svelte
<script lang="ts" context="module">
  import { cva, type VariantProps } from "class-variance-authority"

  import { cn } from "./utils/cn"
  import { focusRing } from "./utils/styles"

  const button = cva(
    cn(
      "inline-flex items-center justify-center gap-2 rounded-md text-sm font-medium",
      focusRing
    ),
    {
      variants: {
        variant: {
          default:
            "bg-button text-foreground hover:bg-button-hover active:bg-button",
          outline:
            "bg-transparent text-foreground border border-input bg-transparent hover:bg-hover",
          ghost: "bg-transparent text-foreground hover:bg-hover",
        },
        size: {
          default: "h-10 px-4 py-2",
          icon: "h-10 w-10 min-w-[theme(width.10)] min-h-[theme(height.10)] max-w-[theme(width.10)] max-h-[theme(height.10)]",
        },
        disabled: {
          true: "opacity-50 pointer-events-none",
        },
      },
      defaultVariants: {
        variant: "default",
        size: "default",
      },
    }
  )
</script>

<script lang="ts">
  let className = ""
  export { className as class }
  export let variant: VariantProps<typeof button>["variant"] = undefined
  export let size: VariantProps<typeof button>["size"] = undefined
  export let disabled = false
</script>

<button
  {disabled}
  on:click
  class={cn(button({ variant, size, disabled }), className)}
>
  <slot />
</button>
