// src/components/ui/textarea.tsx
import * as React from "react"

import { cn } from "~/utils/utils"

export type TextareaProps = React.TextareaHTMLAttributes<HTMLTextAreaElement>

const Textarea = React.forwardRef<HTMLTextAreaElement, TextareaProps>(
  ({ className, ...props }, ref) => {
    return (
      <textarea
        className={cn(
          "flex min-h-[80px] w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50",
          className
        )}
        ref={ref}
        {...props}
      />
    )
  }
)
Textarea.displayName = "Textarea"

export { Textarea }

// src/lib/TextArea.svelte
<script lang="ts" context="module">
  import { cn } from "./utils/cn"
  import { focusRing } from "./utils/styles"
</script>

<script lang="ts">
  let className = ""
  export { className as class }
  export let value = ""
  export let onInput: (value: string) => void = () => null
  export let readonly = false

  const getEventValue = (event: Event) =>
    (event.target as HTMLTextAreaElement).value
</script>

<textarea
  {readonly}
  {value}
  on:input={event => onInput(getEventValue(event))}
  class={cn(
    focusRing,
    "bg-background border border-border rounded-md text-foreground p-4 w-full resize-none",
    "read-only:text-muted-foreground",
    className
  )}
/>
